gems:
  - jekyll-assets
  - jekyll-paginate

markdown: kramdown
highlighter: pygments

#baseurl: /curriculr

# collections:
#   docs:
#     output: true
#   tutorials:
#     output: true

# Assets
assets:
  sources:
    - _assets
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
